// Compiled by ClojureScript 1.9.946 {:static-fns true, :optimize-constants true}
goog.provide('pages.index');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('javelin.core');
goog.require('hoplon_drift.hoplon');
goog.require('hoplon_drift.api.widget');
hoplon.core.html.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__20780 = (hoplon.core.title.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.title.cljs$core$IFn$_invoke$arity$1("Hoplon Drift test") : hoplon.core.title.call(null,"Hoplon Drift test"));
var G__20781 = hoplon_drift.hoplon.snippet.cljs$core$IFn$_invoke$arity$0();
return (hoplon.core.head.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.head.cljs$core$IFn$_invoke$arity$2(G__20780,G__20781) : hoplon.core.head.call(null,G__20780,G__20781));
})(),(function (){var G__20782 = (hoplon.core.div.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.div.cljs$core$IFn$_invoke$arity$1("Hi") : hoplon.core.div.call(null,"Hi"));
var G__20783 = (function (){var G__20785 = cljs.core.cst$kw$click;
var G__20786 = hoplon_drift.api.widget.show_BANG_;
var G__20787 = "Show widget";
return (hoplon.core.button.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.button.cljs$core$IFn$_invoke$arity$3(G__20785,G__20786,G__20787) : hoplon.core.button.call(null,G__20785,G__20786,G__20787));
})();
var G__20784 = (function (){var G__20788 = cljs.core.cst$kw$click;
var G__20789 = hoplon_drift.api.widget.hide_BANG_;
var G__20790 = "Hide widget";
return (hoplon.core.button.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.button.cljs$core$IFn$_invoke$arity$3(G__20788,G__20789,G__20790) : hoplon.core.button.call(null,G__20788,G__20789,G__20790));
})();
return (hoplon.core.body.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.body.cljs$core$IFn$_invoke$arity$3(G__20782,G__20783,G__20784) : hoplon.core.body.call(null,G__20782,G__20783,G__20784));
})()], 0));
